//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_chris_ur5_3f_gripper : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabTrigger
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_GrabTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single SqueezeTrigger
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_SqueezeTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchTrackpad
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_TouchTrackpad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPosition
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_TouchPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressTrackpad
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_PressTrackpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressEast
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_PressEast;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressWest
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_PressWest;
            }
        }
        
        public virtual SteamVR_Action_Boolean Press_Menu
        {
            get
            {
                return SteamVR_Actions.chris_ur5_3f_gripper_Press_Menu;
            }
        }
    }
}
