//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ChrisUr5Moveit
{
    [Serializable]
    public class SdofTranslationMsg : Message
    {
        public const string k_RosMessageName = "chris_ur5_moveit/SdofTranslation";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg destination;
        public Moveit.OrientationConstraintMsg orientation_constraint;

        public SdofTranslationMsg()
        {
            this.destination = new Geometry.PoseMsg();
            this.orientation_constraint = new Moveit.OrientationConstraintMsg();
        }

        public SdofTranslationMsg(Geometry.PoseMsg destination, Moveit.OrientationConstraintMsg orientation_constraint)
        {
            this.destination = destination;
            this.orientation_constraint = orientation_constraint;
        }

        public static SdofTranslationMsg Deserialize(MessageDeserializer deserializer) => new SdofTranslationMsg(deserializer);

        private SdofTranslationMsg(MessageDeserializer deserializer)
        {
            this.destination = Geometry.PoseMsg.Deserialize(deserializer);
            this.orientation_constraint = Moveit.OrientationConstraintMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.destination);
            serializer.Write(this.orientation_constraint);
        }

        public override string ToString()
        {
            return "SdofTranslationMsg: " +
            "\ndestination: " + destination.ToString() +
            "\norientation_constraint: " + orientation_constraint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
