//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ChrisUr5Moveit
{
    [Serializable]
    public class SdofRotationMsg : Message
    {
        public const string k_RosMessageName = "chris_ur5_moveit/SdofRotation";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg destination;
        public Moveit.PositionConstraintMsg position_constraint;

        public SdofRotationMsg()
        {
            this.destination = new Geometry.PoseMsg();
            this.position_constraint = new Moveit.PositionConstraintMsg();
        }

        public SdofRotationMsg(Geometry.PoseMsg destination, Moveit.PositionConstraintMsg position_constraint)
        {
            this.destination = destination;
            this.position_constraint = position_constraint;
        }

        public static SdofRotationMsg Deserialize(MessageDeserializer deserializer) => new SdofRotationMsg(deserializer);

        private SdofRotationMsg(MessageDeserializer deserializer)
        {
            this.destination = Geometry.PoseMsg.Deserialize(deserializer);
            this.position_constraint = Moveit.PositionConstraintMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.destination);
            serializer.Write(this.position_constraint);
        }

        public override string ToString()
        {
            return "SdofRotationMsg: " +
            "\ndestination: " + destination.ToString() +
            "\nposition_constraint: " + position_constraint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
