//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ChrisUr5Moveit
{
    [Serializable]
    public class MoveArmServiceResponse : Message
    {
        public const string k_RosMessageName = "chris_ur5_moveit/MoveArmService";
        public override string RosMessageName => k_RosMessageName;

        public Std.BoolMsg success;

        public MoveArmServiceResponse()
        {
            this.success = new Std.BoolMsg();
        }

        public MoveArmServiceResponse(Std.BoolMsg success)
        {
            this.success = success;
        }

        public static MoveArmServiceResponse Deserialize(MessageDeserializer deserializer) => new MoveArmServiceResponse(deserializer);

        private MoveArmServiceResponse(MessageDeserializer deserializer)
        {
            this.success = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveArmServiceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
