//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ChrisUr5Moveit
{
    [Serializable]
    public class MoveArmServiceRequest : Message
    {
        public const string k_RosMessageName = "chris_ur5_moveit/MoveArmService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg destination;

        public MoveArmServiceRequest()
        {
            this.destination = new Geometry.PoseMsg();
        }

        public MoveArmServiceRequest(Geometry.PoseMsg destination)
        {
            this.destination = destination;
        }

        public static MoveArmServiceRequest Deserialize(MessageDeserializer deserializer) => new MoveArmServiceRequest(deserializer);

        private MoveArmServiceRequest(MessageDeserializer deserializer)
        {
            this.destination = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.destination);
        }

        public override string ToString()
        {
            return "MoveArmServiceRequest: " +
            "\ndestination: " + destination.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
