//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupFeedbackMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  The internal state that the move group action currently is in
        public string state;

        public MoveGroupFeedbackMsg()
        {
            this.state = "";
        }

        public MoveGroupFeedbackMsg(string state)
        {
            this.state = state;
        }

        public static MoveGroupFeedbackMsg Deserialize(MessageDeserializer deserializer) => new MoveGroupFeedbackMsg(deserializer);

        private MoveGroupFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "MoveGroupFeedbackMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
